version: "3.0"
services:
  # minio:
  #   image: minio/minio:RELEASE.2022-04-30T22-23-53Z
  #   ports:
  #     - '9000:9000'
  #     - '9001:9001'
  #   environment:
  #     - 'MINIO_ROOT_USER=ANY'
  #     - 'MINIO_ROOT_PASSWORD=ANY_SECRET'
  #   volumes:
  #     - './${S3_DATA:-docker-compose-init/s3}:/data'
  #   command: server /data --console-address ":9001"
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 4234:5432
    volumes:
      - "./pg_data/:/var/lib/postgresql/data/"
